from PyQt5 import QtCore, QtGui, QtWidgets

import random

userside = []
cmpside = []
UPlay = 1 # guessing
CPlay = -1 # hiding
ulen = 0
clen = 0
last = 0
temp_eq = 50

class Ui_OddOrEven(object):

    def check(self):
        global userside, cmpside
        global UPlay, CPlay
        global ulen, clen
        global last
        global temp_eq
        self.YouWin.setText("")
        self.YouWin_2.setText("")
        val = self.lineEdit.text()
        if last < clen:
            last = clen
        for i in range(last):
            cmpside[i].setPixmap(QtGui.QPixmap("assets/blank.png"))
        cmpside = cmpside[0:temp_eq]
        clen = len(cmpside)
        # i = 0
        # while True:
        #     cmpside[i].setPixmap(QtGui.QPixmap("assets/blank.png"))
        #     i += 1
        #     if len(cmpside) < i:
        #         break
        if val != "":
            val = int(val)
            print(val)
            self.lineEdit.setText("")
            if UPlay == 1:
                clen = len(cmpside)
                cmp_val = random.randint(1, clen)
                cmd = "Machine generated =" + str(cmp_val)
                print(cmp_val)
                self.YouWin_2.setText(cmd)
                for i in range(0, cmp_val):
                    cmpside[i].setPixmap(QtGui.QPixmap("assets/beads.png"))
                for i in range(cmp_val, len(cmpside)):
                    cmpside[i].setPixmap(QtGui.QPixmap("assets/blank.png"))
                if ((val % 2 == 0 and cmp_val % 2 == 0) or (val % 2 == 0 and cmp_val % 2 == 1)):
                    self.label_2.setPixmap(QtGui.QPixmap("assets/even.png"))
                    self.label_7.setPixmap(QtGui.QPixmap("assets/blank.png"))
                    self.label_7.setStyleSheet("background-color:transparent;")
                elif ((val % 2 == 1 and cmp_val % 2 == 0) or (val % 2 == 1 and cmp_val % 2 == 1)):
                    self.label_2.setPixmap(QtGui.QPixmap("assets/odd.png"))
                    self.label_7.setPixmap(QtGui.QPixmap("assets/blank.png"))
                    self.label_7.setStyleSheet("background-color:transparent;")
                if ((val % 2 == cmp_val % 2)):
                    if clen - cmp_val > 0:
                        cmd = str(int(self.label_5.text()) + cmp_val)
                        last = cmp_val
                        self.label_5.setText(cmd)
                        
                        for i in range(clen - cmp_val, cmp_val):
                            userside.append(cmpside[i])
                        temp_eq = clen - cmp_val
                        # cmpside = cmpside[0:clen-cmp_val]
                        clen = len(cmpside) - cmp_val
                        print("ulen = ", len(userside))
                        print("clen = ", len(cmpside))
                    elif ((clen - cmp_val <= 0)):
                        cmd = "You won the match"
                        print(cmd)
                else:
                    ulen = len(userside)
                    if ulen - cmp_val <= 0:
                        cmd = "Opponent won the match"
                        print(cmd)
            else:
                pass
        else:
            self.YouWin_2.setText("Enter a valid input !")
    def restart(self):
        global userside
        global cmpside
        global UPlay, CPlay
        global ulen, clen

        userside = [self.b1_9, self.b2_9, self.b3_9, self.b4_7, self.b5_8, self.b6_10, self.b7_7, self.b8_9, self.b9_10, self.b10_6, self.b1_8, self.b2_10, self.b3_6, self.b4_8, self.b5_9, self.b6_9, self.b7_9, self.b8_7, self.b9_9, self.b10_7, self.b1_9, self.b2_7, self.b3_8, self.b4_9, self.b5_10, self.b6_7, self.b7_3, self.b8_8, self.b9_6, self.b10_9, self.b1_6, self.b2_6, self.b3_7, self.b4_10, self.b5_7, self.b6_6, self.b7_8, self.b8_10, self.b9_8, self.b10_10, self.b1_10, self.b2_8, self.b3_10, self.b4_6, self.b5_6, self.b6_8, self.b7_10, self.b8_6, self.b9_7, self.b10_8]

        cmpside = [self.b1, self.b2, self.b3, self.b4, self.b5, self.b6, self.b7, self.b8, self.b9, self.b10, self.b1_2, self.b2_2, self.b3_2, self.b4_2, self.b5_2, self.b6_2, self.b7_2, self.b8_2, self.b9_2, self.b10_2, self.b1_3, self.b2_3, self.b3_3, self.b4_3, self.b5_3, self.b6_3, self.b7_3, self.b8_3, self.b9_3, self.b10_3, self.b1_4, self.b2_4, self.b3_4, self.b4_4, self.b5_4, self.b6_4, self.b7_4, self.b8_4, self.b9_4, self.b10_4, self.b1_5, self.b2_5, self.b3_5, self.b4_5, self.b5_5, self.b6_5, self.b7_5, self.b8_5, self.b9_5, self.b10_5]
        UPlay = 1
        CPlay = -1
        ulen = len(userside)
        clen = len(cmpside)
            

    def setupUi(self, OddOrEven):
        OddOrEven.setObjectName("OddOrEven")
        OddOrEven.resize(600, 900)
        OddOrEven.setMinimumSize(QtCore.QSize(600, 900))
        OddOrEven.setMaximumSize(QtCore.QSize(600, 900))
        OddOrEven.setStyleSheet("background-color:skyblue;")
        self.centralwidget = QtWidgets.QWidget(OddOrEven)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 70, 541, 261))
        self.label.setStyleSheet("background-color:white;border-radius:10px")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("assets/0dot.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 430, 521, 221))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:white;border-radius:10px")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("assets/closedhandnew.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.YouWin = QtWidgets.QLabel(self.centralwidget)
        self.YouWin.setGeometry(QtCore.QRect(30, 350, 541, 41))
        self.YouWin.setStyleSheet("")
        self.YouWin.setText("")
        self.YouWin.setAlignment(QtCore.Qt.AlignCenter)
        self.YouWin.setObjectName("YouWin")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(310, 750, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("outline:none; border:0px;border-radius:10px;padding:5px;background-color:white;")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 750, 260, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color:white;border-radius:10px;padding:10px;")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(141, 761, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:transparent;")
        self.label_5.setObjectName("label_5")
        self.b1 = QtWidgets.QLabel(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(50, 90, 41, 41))
        self.b1.setStyleSheet("background-color:white;")
        self.b1.setText("")
        self.b1.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1.setScaledContents(True)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QLabel(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(101, 90, 41, 41))
        self.b2.setStyleSheet("background-color:white;")
        self.b2.setText("")
        self.b2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2.setScaledContents(True)
        self.b2.setObjectName("b2")
        self.b3 = QtWidgets.QLabel(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(154, 90, 41, 41))
        self.b3.setStyleSheet("background-color:white;")
        self.b3.setText("")
        self.b3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3.setScaledContents(True)
        self.b3.setObjectName("b3")
        self.b4 = QtWidgets.QLabel(self.centralwidget)
        self.b4.setGeometry(QtCore.QRect(204, 90, 41, 41))
        self.b4.setStyleSheet("background-color:white;")
        self.b4.setText("")
        self.b4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4.setScaledContents(True)
        self.b4.setObjectName("b4")
        self.b6 = QtWidgets.QLabel(self.centralwidget)
        self.b6.setGeometry(QtCore.QRect(308, 90, 41, 41))
        self.b6.setStyleSheet("background-color:white;")
        self.b6.setText("")
        self.b6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6.setScaledContents(True)
        self.b6.setObjectName("b6")
        self.b5 = QtWidgets.QLabel(self.centralwidget)
        self.b5.setGeometry(QtCore.QRect(255, 90, 41, 41))
        self.b5.setStyleSheet("background-color:white;")
        self.b5.setText("")
        self.b5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5.setScaledContents(True)
        self.b5.setObjectName("b5")
        self.b7 = QtWidgets.QLabel(self.centralwidget)
        self.b7.setGeometry(QtCore.QRect(359, 90, 41, 41))
        self.b7.setStyleSheet("background-color:white;")
        self.b7.setText("")
        self.b7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7.setScaledContents(True)
        self.b7.setObjectName("b7")
        self.b9 = QtWidgets.QLabel(self.centralwidget)
        self.b9.setGeometry(QtCore.QRect(463, 90, 41, 41))
        self.b9.setStyleSheet("background-color:white;")
        self.b9.setText("")
        self.b9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9.setScaledContents(True)
        self.b9.setObjectName("b9")
        self.b8 = QtWidgets.QLabel(self.centralwidget)
        self.b8.setGeometry(QtCore.QRect(410, 90, 41, 41))
        self.b8.setStyleSheet("background-color:white;")
        self.b8.setText("")
        self.b8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8.setScaledContents(True)
        self.b8.setObjectName("b8")
        self.b10 = QtWidgets.QLabel(self.centralwidget)
        self.b10.setGeometry(QtCore.QRect(513, 90, 41, 41))
        self.b10.setStyleSheet("background-color:white;")
        self.b10.setText("")
        self.b10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10.setScaledContents(True)
        self.b10.setObjectName("b10")
        self.b6_2 = QtWidgets.QLabel(self.centralwidget)
        self.b6_2.setGeometry(QtCore.QRect(309, 133, 41, 41))
        self.b6_2.setStyleSheet("background-color:white;")
        self.b6_2.setText("")
        self.b6_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_2.setScaledContents(True)
        self.b6_2.setObjectName("b6_2")
        self.b4_2 = QtWidgets.QLabel(self.centralwidget)
        self.b4_2.setGeometry(QtCore.QRect(205, 133, 41, 41))
        self.b4_2.setStyleSheet("background-color:white;")
        self.b4_2.setText("")
        self.b4_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_2.setScaledContents(True)
        self.b4_2.setObjectName("b4_2")
        self.b10_2 = QtWidgets.QLabel(self.centralwidget)
        self.b10_2.setGeometry(QtCore.QRect(514, 133, 41, 41))
        self.b10_2.setStyleSheet("background-color:white;")
        self.b10_2.setText("")
        self.b10_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_2.setScaledContents(True)
        self.b10_2.setObjectName("b10_2")
        self.b5_2 = QtWidgets.QLabel(self.centralwidget)
        self.b5_2.setGeometry(QtCore.QRect(256, 133, 41, 41))
        self.b5_2.setStyleSheet("background-color:white;")
        self.b5_2.setText("")
        self.b5_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_2.setScaledContents(True)
        self.b5_2.setObjectName("b5_2")
        self.b9_2 = QtWidgets.QLabel(self.centralwidget)
        self.b9_2.setGeometry(QtCore.QRect(464, 133, 41, 41))
        self.b9_2.setStyleSheet("background-color:white;")
        self.b9_2.setText("")
        self.b9_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_2.setScaledContents(True)
        self.b9_2.setObjectName("b9_2")
        self.b1_2 = QtWidgets.QLabel(self.centralwidget)
        self.b1_2.setGeometry(QtCore.QRect(51, 133, 41, 41))
        self.b1_2.setStyleSheet("background-color:white;")
        self.b1_2.setText("")
        self.b1_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_2.setScaledContents(True)
        self.b1_2.setObjectName("b1_2")
        self.b8_2 = QtWidgets.QLabel(self.centralwidget)
        self.b8_2.setGeometry(QtCore.QRect(411, 133, 41, 41))
        self.b8_2.setStyleSheet("background-color:white;")
        self.b8_2.setText("")
        self.b8_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_2.setScaledContents(True)
        self.b8_2.setObjectName("b8_2")
        self.b3_2 = QtWidgets.QLabel(self.centralwidget)
        self.b3_2.setGeometry(QtCore.QRect(155, 133, 41, 41))
        self.b3_2.setStyleSheet("background-color:white;")
        self.b3_2.setText("")
        self.b3_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_2.setScaledContents(True)
        self.b3_2.setObjectName("b3_2")
        self.b7_2 = QtWidgets.QLabel(self.centralwidget)
        self.b7_2.setGeometry(QtCore.QRect(360, 133, 41, 41))
        self.b7_2.setStyleSheet("background-color:white;")
        self.b7_2.setText("")
        self.b7_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_2.setScaledContents(True)
        self.b7_2.setObjectName("b7_2")
        self.b2_2 = QtWidgets.QLabel(self.centralwidget)
        self.b2_2.setGeometry(QtCore.QRect(102, 133, 41, 41))
        self.b2_2.setStyleSheet("background-color:white;")
        self.b2_2.setText("")
        self.b2_2.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_2.setScaledContents(True)
        self.b2_2.setObjectName("b2_2")
        self.b6_3 = QtWidgets.QLabel(self.centralwidget)
        self.b6_3.setGeometry(QtCore.QRect(310, 178, 41, 41))
        self.b6_3.setStyleSheet("background-color:white;")
        self.b6_3.setText("")
        self.b6_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_3.setScaledContents(True)
        self.b6_3.setObjectName("b6_3")
        self.b4_3 = QtWidgets.QLabel(self.centralwidget)
        self.b4_3.setGeometry(QtCore.QRect(206, 178, 41, 41))
        self.b4_3.setStyleSheet("background-color:white;")
        self.b4_3.setText("")
        self.b4_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_3.setScaledContents(True)
        self.b4_3.setObjectName("b4_3")
        self.b10_3 = QtWidgets.QLabel(self.centralwidget)
        self.b10_3.setGeometry(QtCore.QRect(515, 178, 41, 41))
        self.b10_3.setStyleSheet("background-color:white;")
        self.b10_3.setText("")
        self.b10_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_3.setScaledContents(True)
        self.b10_3.setObjectName("b10_3")
        self.b5_3 = QtWidgets.QLabel(self.centralwidget)
        self.b5_3.setGeometry(QtCore.QRect(257, 178, 41, 41))
        self.b5_3.setStyleSheet("background-color:white;")
        self.b5_3.setText("")
        self.b5_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_3.setScaledContents(True)
        self.b5_3.setObjectName("b5_3")
        self.b9_3 = QtWidgets.QLabel(self.centralwidget)
        self.b9_3.setGeometry(QtCore.QRect(465, 178, 41, 41))
        self.b9_3.setStyleSheet("background-color:white;")
        self.b9_3.setText("")
        self.b9_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_3.setScaledContents(True)
        self.b9_3.setObjectName("b9_3")
        self.b1_3 = QtWidgets.QLabel(self.centralwidget)
        self.b1_3.setGeometry(QtCore.QRect(52, 178, 41, 41))
        self.b1_3.setStyleSheet("background-color:white;")
        self.b1_3.setText("")
        self.b1_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_3.setScaledContents(True)
        self.b1_3.setObjectName("b1_3")
        self.b8_3 = QtWidgets.QLabel(self.centralwidget)
        self.b8_3.setGeometry(QtCore.QRect(412, 178, 41, 41))
        self.b8_3.setStyleSheet("background-color:white;")
        self.b8_3.setText("")
        self.b8_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_3.setScaledContents(True)
        self.b8_3.setObjectName("b8_3")
        self.b3_3 = QtWidgets.QLabel(self.centralwidget)
        self.b3_3.setGeometry(QtCore.QRect(156, 178, 41, 41))
        self.b3_3.setStyleSheet("background-color:white;")
        self.b3_3.setText("")
        self.b3_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_3.setScaledContents(True)
        self.b3_3.setObjectName("b3_3")
        self.b7_3 = QtWidgets.QLabel(self.centralwidget)
        self.b7_3.setGeometry(QtCore.QRect(361, 178, 41, 41))
        self.b7_3.setStyleSheet("background-color:white;")
        self.b7_3.setText("")
        self.b7_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_3.setScaledContents(True)
        self.b7_3.setObjectName("b7_3")
        self.b2_3 = QtWidgets.QLabel(self.centralwidget)
        self.b2_3.setGeometry(QtCore.QRect(103, 178, 41, 41))
        self.b2_3.setStyleSheet("background-color:white;")
        self.b2_3.setText("")
        self.b2_3.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_3.setScaledContents(True)
        self.b2_3.setObjectName("b2_3")
        self.b6_4 = QtWidgets.QLabel(self.centralwidget)
        self.b6_4.setGeometry(QtCore.QRect(311, 223, 41, 41))
        self.b6_4.setStyleSheet("background-color:white;")
        self.b6_4.setText("")
        self.b6_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_4.setScaledContents(True)
        self.b6_4.setObjectName("b6_4")
        self.b4_4 = QtWidgets.QLabel(self.centralwidget)
        self.b4_4.setGeometry(QtCore.QRect(207, 223, 41, 41))
        self.b4_4.setStyleSheet("background-color:white;")
        self.b4_4.setText("")
        self.b4_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_4.setScaledContents(True)
        self.b4_4.setObjectName("b4_4")
        self.b10_4 = QtWidgets.QLabel(self.centralwidget)
        self.b10_4.setGeometry(QtCore.QRect(516, 223, 41, 41))
        self.b10_4.setStyleSheet("background-color:white;")
        self.b10_4.setText("")
        self.b10_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_4.setScaledContents(True)
        self.b10_4.setObjectName("b10_4")
        self.b5_4 = QtWidgets.QLabel(self.centralwidget)
        self.b5_4.setGeometry(QtCore.QRect(258, 223, 41, 41))
        self.b5_4.setStyleSheet("background-color:white;")
        self.b5_4.setText("")
        self.b5_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_4.setScaledContents(True)
        self.b5_4.setObjectName("b5_4")
        self.b9_4 = QtWidgets.QLabel(self.centralwidget)
        self.b9_4.setGeometry(QtCore.QRect(466, 223, 41, 41))
        self.b9_4.setStyleSheet("background-color:white;")
        self.b9_4.setText("")
        self.b9_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_4.setScaledContents(True)
        self.b9_4.setObjectName("b9_4")
        self.b1_4 = QtWidgets.QLabel(self.centralwidget)
        self.b1_4.setGeometry(QtCore.QRect(53, 223, 41, 41))
        self.b1_4.setStyleSheet("background-color:white;")
        self.b1_4.setText("")
        self.b1_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_4.setScaledContents(True)
        self.b1_4.setObjectName("b1_4")
        self.b8_4 = QtWidgets.QLabel(self.centralwidget)
        self.b8_4.setGeometry(QtCore.QRect(413, 223, 41, 41))
        self.b8_4.setStyleSheet("background-color:white;")
        self.b8_4.setText("")
        self.b8_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_4.setScaledContents(True)
        self.b8_4.setObjectName("b8_4")
        self.b3_4 = QtWidgets.QLabel(self.centralwidget)
        self.b3_4.setGeometry(QtCore.QRect(157, 223, 41, 41))
        self.b3_4.setStyleSheet("background-color:white;")
        self.b3_4.setText("")
        self.b3_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_4.setScaledContents(True)
        self.b3_4.setObjectName("b3_4")
        self.b7_4 = QtWidgets.QLabel(self.centralwidget)
        self.b7_4.setGeometry(QtCore.QRect(362, 223, 41, 41))
        self.b7_4.setStyleSheet("background-color:white;")
        self.b7_4.setText("")
        self.b7_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_4.setScaledContents(True)
        self.b7_4.setObjectName("b7_4")
        self.b2_4 = QtWidgets.QLabel(self.centralwidget)
        self.b2_4.setGeometry(QtCore.QRect(104, 223, 41, 41))
        self.b2_4.setStyleSheet("background-color:white;")
        self.b2_4.setText("")
        self.b2_4.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_4.setScaledContents(True)
        self.b2_4.setObjectName("b2_4")
        self.b6_5 = QtWidgets.QLabel(self.centralwidget)
        self.b6_5.setGeometry(QtCore.QRect(311, 269, 41, 41))
        self.b6_5.setStyleSheet("background-color:white;")
        self.b6_5.setText("")
        self.b6_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_5.setScaledContents(True)
        self.b6_5.setObjectName("b6_5")
        self.b4_5 = QtWidgets.QLabel(self.centralwidget)
        self.b4_5.setGeometry(QtCore.QRect(207, 269, 41, 41))
        self.b4_5.setStyleSheet("background-color:white;")
        self.b4_5.setText("")
        self.b4_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_5.setScaledContents(True)
        self.b4_5.setObjectName("b4_5")
        self.b10_5 = QtWidgets.QLabel(self.centralwidget)
        self.b10_5.setGeometry(QtCore.QRect(516, 269, 41, 41))
        self.b10_5.setStyleSheet("background-color:white;")
        self.b10_5.setText("")
        self.b10_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_5.setScaledContents(True)
        self.b10_5.setObjectName("b10_5")
        self.b5_5 = QtWidgets.QLabel(self.centralwidget)
        self.b5_5.setGeometry(QtCore.QRect(258, 269, 41, 41))
        self.b5_5.setStyleSheet("background-color:white;")
        self.b5_5.setText("")
        self.b5_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_5.setScaledContents(True)
        self.b5_5.setObjectName("b5_5")
        self.b9_5 = QtWidgets.QLabel(self.centralwidget)
        self.b9_5.setGeometry(QtCore.QRect(466, 269, 41, 41))
        self.b9_5.setStyleSheet("background-color:white;")
        self.b9_5.setText("")
        self.b9_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_5.setScaledContents(True)
        self.b9_5.setObjectName("b9_5")
        self.b1_5 = QtWidgets.QLabel(self.centralwidget)
        self.b1_5.setGeometry(QtCore.QRect(53, 269, 41, 41))
        self.b1_5.setStyleSheet("background-color:white;")
        self.b1_5.setText("")
        self.b1_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_5.setScaledContents(True)
        self.b1_5.setObjectName("b1_5")
        self.b8_5 = QtWidgets.QLabel(self.centralwidget)
        self.b8_5.setGeometry(QtCore.QRect(413, 269, 41, 41))
        self.b8_5.setStyleSheet("background-color:white;")
        self.b8_5.setText("")
        self.b8_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_5.setScaledContents(True)
        self.b8_5.setObjectName("b8_5")
        self.b3_5 = QtWidgets.QLabel(self.centralwidget)
        self.b3_5.setGeometry(QtCore.QRect(157, 269, 41, 41))
        self.b3_5.setStyleSheet("background-color:white;")
        self.b3_5.setText("")
        self.b3_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_5.setScaledContents(True)
        self.b3_5.setObjectName("b3_5")
        self.b7_5 = QtWidgets.QLabel(self.centralwidget)
        self.b7_5.setGeometry(QtCore.QRect(362, 269, 41, 41))
        self.b7_5.setStyleSheet("background-color:white;")
        self.b7_5.setText("")
        self.b7_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_5.setScaledContents(True)
        self.b7_5.setObjectName("b7_5")
        self.b2_5 = QtWidgets.QLabel(self.centralwidget)
        self.b2_5.setGeometry(QtCore.QRect(104, 269, 41, 41))
        self.b2_5.setStyleSheet("background-color:white;")
        self.b2_5.setText("")
        self.b2_5.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_5.setScaledContents(True)
        self.b2_5.setObjectName("b2_5")
        self.b6_6 = QtWidgets.QLabel(self.centralwidget)
        self.b6_6.setGeometry(QtCore.QRect(305, 563, 41, 41))
        self.b6_6.setStyleSheet("background-color:white;")
        self.b6_6.setText("")
        self.b6_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_6.setScaledContents(True)
        self.b6_6.setObjectName("b6_6")
        self.b6_7 = QtWidgets.QLabel(self.centralwidget)
        self.b6_7.setGeometry(QtCore.QRect(304, 518, 41, 41))
        self.b6_7.setStyleSheet("background-color:white;")
        self.b6_7.setText("")
        self.b6_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_7.setScaledContents(True)
        self.b6_7.setObjectName("b6_7")
        self.b5_6 = QtWidgets.QLabel(self.centralwidget)
        self.b5_6.setGeometry(QtCore.QRect(252, 609, 41, 41))
        self.b5_6.setStyleSheet("background-color:white;")
        self.b5_6.setText("")
        self.b5_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_6.setScaledContents(True)
        self.b5_6.setObjectName("b5_6")
        self.b10_6 = QtWidgets.QLabel(self.centralwidget)
        self.b10_6.setGeometry(QtCore.QRect(507, 430, 41, 41))
        self.b10_6.setStyleSheet("background-color:white;")
        self.b10_6.setText("")
        self.b10_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_6.setScaledContents(True)
        self.b10_6.setObjectName("b10_6")
        self.b8_6 = QtWidgets.QLabel(self.centralwidget)
        self.b8_6.setGeometry(QtCore.QRect(407, 609, 41, 41))
        self.b8_6.setStyleSheet("background-color:white;")
        self.b8_6.setText("")
        self.b8_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_6.setScaledContents(True)
        self.b8_6.setObjectName("b8_6")
        self.b7_6 = QtWidgets.QLabel(self.centralwidget)
        self.b7_6.setGeometry(QtCore.QRect(355, 518, 41, 41))
        self.b7_6.setStyleSheet("background-color:white;")
        self.b7_6.setText("")
        self.b7_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_6.setScaledContents(True)
        self.b7_6.setObjectName("b7_6")
        self.b9_6 = QtWidgets.QLabel(self.centralwidget)
        self.b9_6.setGeometry(QtCore.QRect(459, 518, 41, 41))
        self.b9_6.setStyleSheet("background-color:white;")
        self.b9_6.setText("")
        self.b9_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_6.setScaledContents(True)
        self.b9_6.setObjectName("b9_6")
        self.b5_7 = QtWidgets.QLabel(self.centralwidget)
        self.b5_7.setGeometry(QtCore.QRect(252, 563, 41, 41))
        self.b5_7.setStyleSheet("background-color:white;")
        self.b5_7.setText("")
        self.b5_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_7.setScaledContents(True)
        self.b5_7.setObjectName("b5_7")
        self.b2_6 = QtWidgets.QLabel(self.centralwidget)
        self.b2_6.setGeometry(QtCore.QRect(98, 563, 41, 41))
        self.b2_6.setStyleSheet("background-color:white;")
        self.b2_6.setText("")
        self.b2_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_6.setScaledContents(True)
        self.b2_6.setObjectName("b2_6")
        self.b9_7 = QtWidgets.QLabel(self.centralwidget)
        self.b9_7.setGeometry(QtCore.QRect(460, 609, 41, 41))
        self.b9_7.setStyleSheet("background-color:white;")
        self.b9_7.setText("")
        self.b9_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_7.setScaledContents(True)
        self.b9_7.setObjectName("b9_7")
        self.b4_6 = QtWidgets.QLabel(self.centralwidget)
        self.b4_6.setGeometry(QtCore.QRect(201, 609, 41, 41))
        self.b4_6.setStyleSheet("background-color:white;")
        self.b4_6.setText("")
        self.b4_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_6.setScaledContents(True)
        self.b4_6.setObjectName("b4_6")
        self.b5_8 = QtWidgets.QLabel(self.centralwidget)
        self.b5_8.setGeometry(QtCore.QRect(249, 430, 41, 41))
        self.b5_8.setStyleSheet("background-color:white;")
        self.b5_8.setText("")
        self.b5_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_8.setScaledContents(True)
        self.b5_8.setObjectName("b5_8")
        self.b3_6 = QtWidgets.QLabel(self.centralwidget)
        self.b3_6.setGeometry(QtCore.QRect(149, 473, 41, 41))
        self.b3_6.setStyleSheet("background-color:white;")
        self.b3_6.setText("")
        self.b3_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_6.setScaledContents(True)
        self.b3_6.setObjectName("b3_6")
        self.b1_6 = QtWidgets.QLabel(self.centralwidget)
        self.b1_6.setGeometry(QtCore.QRect(47, 563, 41, 41))
        self.b1_6.setStyleSheet("background-color:white;")
        self.b1_6.setText("")
        self.b1_6.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_6.setScaledContents(True)
        self.b1_6.setObjectName("b1_6")
        self.b10_7 = QtWidgets.QLabel(self.centralwidget)
        self.b10_7.setGeometry(QtCore.QRect(508, 473, 41, 41))
        self.b10_7.setStyleSheet("background-color:white;")
        self.b10_7.setText("")
        self.b10_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_7.setScaledContents(True)
        self.b10_7.setObjectName("b10_7")
        self.b7_7 = QtWidgets.QLabel(self.centralwidget)
        self.b7_7.setGeometry(QtCore.QRect(353, 430, 41, 41))
        self.b7_7.setStyleSheet("background-color:white;")
        self.b7_7.setText("")
        self.b7_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_7.setScaledContents(True)
        self.b7_7.setObjectName("b7_7")
        self.b2_7 = QtWidgets.QLabel(self.centralwidget)
        self.b2_7.setGeometry(QtCore.QRect(97, 518, 41, 41))
        self.b2_7.setStyleSheet("background-color:white;")
        self.b2_7.setText("")
        self.b2_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_7.setScaledContents(True)
        self.b2_7.setObjectName("b2_7")
        self.b3_7 = QtWidgets.QLabel(self.centralwidget)
        self.b3_7.setGeometry(QtCore.QRect(151, 563, 41, 41))
        self.b3_7.setStyleSheet("background-color:white;")
        self.b3_7.setText("")
        self.b3_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_7.setScaledContents(True)
        self.b3_7.setObjectName("b3_7")
        self.b5_9 = QtWidgets.QLabel(self.centralwidget)
        self.b5_9.setGeometry(QtCore.QRect(250, 473, 41, 41))
        self.b5_9.setStyleSheet("background-color:white;")
        self.b5_9.setText("")
        self.b5_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_9.setScaledContents(True)
        self.b5_9.setObjectName("b5_9")
        self.b6_8 = QtWidgets.QLabel(self.centralwidget)
        self.b6_8.setGeometry(QtCore.QRect(305, 609, 41, 41))
        self.b6_8.setStyleSheet("background-color:white;")
        self.b6_8.setText("")
        self.b6_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_8.setScaledContents(True)
        self.b6_8.setObjectName("b6_8")
        self.b3_8 = QtWidgets.QLabel(self.centralwidget)
        self.b3_8.setGeometry(QtCore.QRect(150, 518, 41, 41))
        self.b3_8.setStyleSheet("background-color:white;")
        self.b3_8.setText("")
        self.b3_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_8.setScaledContents(True)
        self.b3_8.setObjectName("b3_8")
        self.b2_8 = QtWidgets.QLabel(self.centralwidget)
        self.b2_8.setGeometry(QtCore.QRect(98, 609, 41, 41))
        self.b2_8.setStyleSheet("background-color:white;")
        self.b2_8.setText("")
        self.b2_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_8.setScaledContents(True)
        self.b2_8.setObjectName("b2_8")
        self.b8_7 = QtWidgets.QLabel(self.centralwidget)
        self.b8_7.setGeometry(QtCore.QRect(405, 473, 41, 41))
        self.b8_7.setStyleSheet("background-color:white;")
        self.b8_7.setText("")
        self.b8_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_7.setScaledContents(True)
        self.b8_7.setObjectName("b8_7")
        self.b2_9 = QtWidgets.QLabel(self.centralwidget)
        self.b2_9.setGeometry(QtCore.QRect(95, 430, 41, 41))
        self.b2_9.setStyleSheet("background-color:white;")
        self.b2_9.setText("")
        self.b2_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_9.setScaledContents(True)
        self.b2_9.setObjectName("b2_9")
        self.b5_10 = QtWidgets.QLabel(self.centralwidget)
        self.b5_10.setGeometry(QtCore.QRect(251, 518, 41, 41))
        self.b5_10.setStyleSheet("background-color:white;")
        self.b5_10.setText("")
        self.b5_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b5_10.setScaledContents(True)
        self.b5_10.setObjectName("b5_10")
        self.b7_8 = QtWidgets.QLabel(self.centralwidget)
        self.b7_8.setGeometry(QtCore.QRect(356, 563, 41, 41))
        self.b7_8.setStyleSheet("background-color:white;")
        self.b7_8.setText("")
        self.b7_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_8.setScaledContents(True)
        self.b7_8.setObjectName("b7_8")
        self.b9_8 = QtWidgets.QLabel(self.centralwidget)
        self.b9_8.setGeometry(QtCore.QRect(460, 563, 41, 41))
        self.b9_8.setStyleSheet("background-color:white;")
        self.b9_8.setText("")
        self.b9_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_8.setScaledContents(True)
        self.b9_8.setObjectName("b9_8")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(32, 410, 541, 261))
        self.label_6.setStyleSheet("background-color:white;border-radius:10px")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("assets/0dot.png"))
        self.label_6.setObjectName("label_6")
        self.b3_9 = QtWidgets.QLabel(self.centralwidget)
        self.b3_9.setGeometry(QtCore.QRect(148, 430, 41, 41))
        self.b3_9.setStyleSheet("background-color:white;")
        self.b3_9.setText("")
        self.b3_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_9.setScaledContents(True)
        self.b3_9.setObjectName("b3_9")
        self.b3_10 = QtWidgets.QLabel(self.centralwidget)
        self.b3_10.setGeometry(QtCore.QRect(151, 609, 41, 41))
        self.b3_10.setStyleSheet("background-color:white;")
        self.b3_10.setText("")
        self.b3_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b3_10.setScaledContents(True)
        self.b3_10.setObjectName("b3_10")
        self.b8_8 = QtWidgets.QLabel(self.centralwidget)
        self.b8_8.setGeometry(QtCore.QRect(406, 518, 41, 41))
        self.b8_8.setStyleSheet("background-color:white;")
        self.b8_8.setText("")
        self.b8_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_8.setScaledContents(True)
        self.b8_8.setObjectName("b8_8")
        self.b10_8 = QtWidgets.QLabel(self.centralwidget)
        self.b10_8.setGeometry(QtCore.QRect(510, 609, 41, 41))
        self.b10_8.setStyleSheet("background-color:white;")
        self.b10_8.setText("")
        self.b10_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_8.setScaledContents(True)
        self.b10_8.setObjectName("b10_8")
        self.b4_7 = QtWidgets.QLabel(self.centralwidget)
        self.b4_7.setGeometry(QtCore.QRect(198, 430, 41, 41))
        self.b4_7.setStyleSheet("background-color:white;")
        self.b4_7.setText("")
        self.b4_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_7.setScaledContents(True)
        self.b4_7.setObjectName("b4_7")
        self.b10_9 = QtWidgets.QLabel(self.centralwidget)
        self.b10_9.setGeometry(QtCore.QRect(509, 518, 41, 41))
        self.b10_9.setStyleSheet("background-color:white;")
        self.b10_9.setText("")
        self.b10_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_9.setScaledContents(True)
        self.b10_9.setObjectName("b10_9")
        self.b10_10 = QtWidgets.QLabel(self.centralwidget)
        self.b10_10.setGeometry(QtCore.QRect(510, 563, 41, 41))
        self.b10_10.setStyleSheet("background-color:white;")
        self.b10_10.setText("")
        self.b10_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b10_10.setScaledContents(True)
        self.b10_10.setObjectName("b10_10")
        self.b1_7 = QtWidgets.QLabel(self.centralwidget)
        self.b1_7.setGeometry(QtCore.QRect(44, 430, 41, 41))
        self.b1_7.setStyleSheet("background-color:white;")
        self.b1_7.setText("")
        self.b1_7.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_7.setScaledContents(True)
        self.b1_7.setObjectName("b1_7")
        self.b8_9 = QtWidgets.QLabel(self.centralwidget)
        self.b8_9.setGeometry(QtCore.QRect(404, 430, 41, 41))
        self.b8_9.setStyleSheet("background-color:white;")
        self.b8_9.setText("")
        self.b8_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_9.setScaledContents(True)
        self.b8_9.setObjectName("b8_9")
        self.b4_8 = QtWidgets.QLabel(self.centralwidget)
        self.b4_8.setGeometry(QtCore.QRect(199, 473, 41, 41))
        self.b4_8.setStyleSheet("background-color:white;")
        self.b4_8.setText("")
        self.b4_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_8.setScaledContents(True)
        self.b4_8.setObjectName("b4_8")
        self.b7_9 = QtWidgets.QLabel(self.centralwidget)
        self.b7_9.setGeometry(QtCore.QRect(354, 473, 41, 41))
        self.b7_9.setStyleSheet("background-color:white;")
        self.b7_9.setText("")
        self.b7_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_9.setScaledContents(True)
        self.b7_9.setObjectName("b7_9")
        self.b8_10 = QtWidgets.QLabel(self.centralwidget)
        self.b8_10.setGeometry(QtCore.QRect(407, 563, 41, 41))
        self.b8_10.setStyleSheet("background-color:white;")
        self.b8_10.setText("")
        self.b8_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b8_10.setScaledContents(True)
        self.b8_10.setObjectName("b8_10")
        self.b7_10 = QtWidgets.QLabel(self.centralwidget)
        self.b7_10.setGeometry(QtCore.QRect(356, 609, 41, 41))
        self.b7_10.setStyleSheet("background-color:white;")
        self.b7_10.setText("")
        self.b7_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b7_10.setScaledContents(True)
        self.b7_10.setObjectName("b7_10")
        self.b6_9 = QtWidgets.QLabel(self.centralwidget)
        self.b6_9.setGeometry(QtCore.QRect(303, 473, 41, 41))
        self.b6_9.setStyleSheet("background-color:white;")
        self.b6_9.setText("")
        self.b6_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_9.setScaledContents(True)
        self.b6_9.setObjectName("b6_9")
        self.b1_8 = QtWidgets.QLabel(self.centralwidget)
        self.b1_8.setGeometry(QtCore.QRect(45, 473, 41, 41))
        self.b1_8.setStyleSheet("background-color:white;")
        self.b1_8.setText("")
        self.b1_8.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_8.setScaledContents(True)
        self.b1_8.setObjectName("b1_8")
        self.b6_10 = QtWidgets.QLabel(self.centralwidget)
        self.b6_10.setGeometry(QtCore.QRect(302, 430, 41, 41))
        self.b6_10.setStyleSheet("background-color:white;")
        self.b6_10.setText("")
        self.b6_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b6_10.setScaledContents(True)
        self.b6_10.setObjectName("b6_10")
        self.b2_10 = QtWidgets.QLabel(self.centralwidget)
        self.b2_10.setGeometry(QtCore.QRect(96, 473, 41, 41))
        self.b2_10.setStyleSheet("background-color:white;")
        self.b2_10.setText("")
        self.b2_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b2_10.setScaledContents(True)
        self.b2_10.setObjectName("b2_10")
        self.b1_9 = QtWidgets.QLabel(self.centralwidget)
        self.b1_9.setGeometry(QtCore.QRect(46, 518, 41, 41))
        self.b1_9.setStyleSheet("background-color:white;")
        self.b1_9.setText("")
        self.b1_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_9.setScaledContents(True)
        self.b1_9.setObjectName("b1_9")
        self.b4_9 = QtWidgets.QLabel(self.centralwidget)
        self.b4_9.setGeometry(QtCore.QRect(200, 518, 41, 41))
        self.b4_9.setStyleSheet("background-color:white;")
        self.b4_9.setText("")
        self.b4_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_9.setScaledContents(True)
        self.b4_9.setObjectName("b4_9")
        self.b1_10 = QtWidgets.QLabel(self.centralwidget)
        self.b1_10.setGeometry(QtCore.QRect(47, 609, 41, 41))
        self.b1_10.setStyleSheet("background-color:white;")
        self.b1_10.setText("")
        self.b1_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b1_10.setScaledContents(True)
        self.b1_10.setObjectName("b1_10")
        self.b9_9 = QtWidgets.QLabel(self.centralwidget)
        self.b9_9.setGeometry(QtCore.QRect(458, 473, 41, 41))
        self.b9_9.setStyleSheet("background-color:white;")
        self.b9_9.setText("")
        self.b9_9.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_9.setScaledContents(True)
        self.b9_9.setObjectName("b9_9")
        self.b4_10 = QtWidgets.QLabel(self.centralwidget)
        self.b4_10.setGeometry(QtCore.QRect(201, 563, 41, 41))
        self.b4_10.setStyleSheet("background-color:white;")
        self.b4_10.setText("")
        self.b4_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b4_10.setScaledContents(True)
        self.b4_10.setObjectName("b4_10")
        self.b9_10 = QtWidgets.QLabel(self.centralwidget)
        self.b9_10.setGeometry(QtCore.QRect(457, 430, 41, 41))
        self.b9_10.setStyleSheet("background-color:white;")
        self.b9_10.setText("")
        self.b9_10.setPixmap(QtGui.QPixmap("assets/beads.png"))
        self.b9_10.setScaledContents(True)
        self.b9_10.setObjectName("b9_10")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 90, 521, 221))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:white;border-radius:10px")
        self.label_7.setText("")
        self.label_7.setPixmap(QtGui.QPixmap("assets/closedhandnew2.png"))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(540, 10, 41, 41))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("assets/info.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.info = QtWidgets.QPushButton(self.centralwidget)
        self.info.setGeometry(QtCore.QRect(540, 10, 41, 41))
        self.info.setStyleSheet("background-color:transparent;border:none;outline:none;")
        self.info.setText("")
        self.info.setObjectName("info")
        self.YouWin_2 = QtWidgets.QLabel(self.centralwidget)
        self.YouWin_2.setGeometry(QtCore.QRect(30, 690, 541, 41))
        self.YouWin_2.setStyleSheet("")
        self.YouWin_2.setText("")
        self.YouWin_2.setAlignment(QtCore.Qt.AlignCenter)
        self.YouWin_2.setObjectName("YouWin_2")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 806, 260, 41))
        self.pushButton_8.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:white;\n"
"    color:red;\n"
"    outline:none;\n"
"    border-radius:10px;\n"
"    border:0px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:red;\n"
"    color:white;\n"
"    border:1px solid white;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.Quit = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.restart())
        self.Quit.clicked.connect(OddOrEven.close)
        self.Quit.setGeometry(QtCore.QRect(310, 806, 260, 41))
        self.Quit.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:white;\n"
"    color:red;\n"
"    outline:none;\n"
"    border-radius:10px;\n"
"    border:0px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color:red;\n"
"    color:white;\n"
"    border:1px solid white;\n"
"}")
        self.Quit.setObjectName("Quit")
        self.OK = QtWidgets.QPushButton(self.centralwidget, clicked = lambda : self.check())
        self.OK.setGeometry(QtCore.QRect(510, 751, 57, 40))
        self.OK.setStyleSheet("background-color:white; border:none; outline:none;border-radius:10px;")
        self.OK.setObjectName("OK")
        self.label_6.raise_()
        self.label.raise_()
        self.YouWin.raise_()
        self.lineEdit.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.b1.raise_()
        self.b2.raise_()
        self.b3.raise_()
        self.b4.raise_()
        self.b6.raise_()
        self.b5.raise_()
        self.b7.raise_()
        self.b9.raise_()
        self.b8.raise_()
        self.b10.raise_()
        self.b6_2.raise_()
        self.b4_2.raise_()
        self.b10_2.raise_()
        self.b5_2.raise_()
        self.b9_2.raise_()
        self.b1_2.raise_()
        self.b8_2.raise_()
        self.b3_2.raise_()
        self.b7_2.raise_()
        self.b2_2.raise_()
        self.b6_3.raise_()
        self.b4_3.raise_()
        self.b10_3.raise_()
        self.b5_3.raise_()
        self.b9_3.raise_()
        self.b1_3.raise_()
        self.b8_3.raise_()
        self.b3_3.raise_()
        self.b7_3.raise_()
        self.b2_3.raise_()
        self.b6_4.raise_()
        self.b4_4.raise_()
        self.b10_4.raise_()
        self.b5_4.raise_()
        self.b9_4.raise_()
        self.b1_4.raise_()
        self.b8_4.raise_()
        self.b3_4.raise_()
        self.b7_4.raise_()
        self.b2_4.raise_()
        self.b6_5.raise_()
        self.b4_5.raise_()
        self.b10_5.raise_()
        self.b5_5.raise_()
        self.b9_5.raise_()
        self.b1_5.raise_()
        self.b8_5.raise_()
        self.b3_5.raise_()
        self.b7_5.raise_()
        self.b2_5.raise_()
        self.b6_6.raise_()
        self.b6_7.raise_()
        self.b5_6.raise_()
        self.b10_6.raise_()
        self.b8_6.raise_()
        self.b7_6.raise_()
        self.b9_6.raise_()
        self.b5_7.raise_()
        self.b2_6.raise_()
        self.b9_7.raise_()
        self.b4_6.raise_()
        self.b5_8.raise_()
        self.b3_6.raise_()
        self.b1_6.raise_()
        self.b10_7.raise_()
        self.b7_7.raise_()
        self.b2_7.raise_()
        self.b3_7.raise_()
        self.b5_9.raise_()
        self.b6_8.raise_()
        self.b3_8.raise_()
        self.b2_8.raise_()
        self.b8_7.raise_()
        self.b2_9.raise_()
        self.b5_10.raise_()
        self.b7_8.raise_()
        self.b9_8.raise_()
        self.b3_9.raise_()
        self.b3_10.raise_()
        self.b8_8.raise_()
        self.b10_8.raise_()
        self.b4_7.raise_()
        self.b10_9.raise_()
        self.b10_10.raise_()
        self.b1_7.raise_()
        self.b8_9.raise_()
        self.b4_8.raise_()
        self.b7_9.raise_()
        self.b8_10.raise_()
        self.b7_10.raise_()
        self.b6_9.raise_()
        self.b1_8.raise_()
        self.b6_10.raise_()
        self.b2_10.raise_()
        self.b1_9.raise_()
        self.b4_9.raise_()
        self.b1_10.raise_()
        self.b9_9.raise_()
        self.b4_10.raise_()
        self.b9_10.raise_()
        self.label_2.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.info.raise_()
        self.YouWin_2.raise_()
        self.pushButton_8.raise_()
        self.Quit.raise_()
        self.OK.raise_()
        OddOrEven.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OddOrEven)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 26))
        self.menubar.setObjectName("menubar")
        OddOrEven.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OddOrEven)
        self.statusbar.setObjectName("statusbar")
        OddOrEven.setStatusBar(self.statusbar)

        self.retranslateUi(OddOrEven)
        QtCore.QMetaObject.connectSlotsByName(OddOrEven)

        global userside
        global cmpside

        userside = [self.b1_9, self.b2_9, self.b3_9, self.b4_7, self.b5_8, self.b6_10, self.b7_7, self.b8_9, self.b9_10, self.b10_6, self.b1_8, self.b2_10, self.b3_6, self.b4_8, self.b5_9, self.b6_9, self.b7_9, self.b8_7, self.b9_9, self.b10_7, self.b1_9, self.b2_7, self.b3_8, self.b4_9, self.b5_10, self.b6_7, self.b7_3, self.b8_8, self.b9_6, self.b10_9, self.b1_6, self.b2_6, self.b3_7, self.b4_10, self.b5_7, self.b6_6, self.b7_8, self.b8_10, self.b9_8, self.b10_10, self.b1_10, self.b2_8, self.b3_10, self.b4_6, self.b5_6, self.b6_8, self.b7_10, self.b8_6, self.b9_7, self.b10_8]

        cmpside = [self.b1, self.b2, self.b3, self.b4, self.b5, self.b6, self.b7, self.b8, self.b9, self.b10, self.b1_2, self.b2_2, self.b3_2, self.b4_2, self.b5_2, self.b6_2, self.b7_2, self.b8_2, self.b9_2, self.b10_2, self.b1_3, self.b2_3, self.b3_3, self.b4_3, self.b5_3, self.b6_3, self.b7_3, self.b8_3, self.b9_3, self.b10_3, self.b1_4, self.b2_4, self.b3_4, self.b4_4, self.b5_4, self.b6_4, self.b7_4, self.b8_4, self.b9_4, self.b10_4, self.b1_5, self.b2_5, self.b3_5, self.b4_5, self.b5_5, self.b6_5, self.b7_5, self.b8_5, self.b9_5, self.b10_5]

    def retranslateUi(self, OddOrEven):
        _translate = QtCore.QCoreApplication.translate
        OddOrEven.setWindowTitle(_translate("OddOrEven", "Odd or Even - Nexus"))
        self.lineEdit.setPlaceholderText(_translate("OddOrEven", "1 [odd] / 2 [even]"))
        self.label_4.setText(_translate("OddOrEven", "You have :"))
        self.label_5.setText(_translate("OddOrEven", "50"))
        self.pushButton_8.setText(_translate("OddOrEven", "Restart"))
        self.Quit.setText(_translate("OddOrEven", "Quit"))
        self.OK.setText(_translate("OddOrEven", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OddOrEven = QtWidgets.QMainWindow()
    ui = Ui_OddOrEven()
    ui.setupUi(OddOrEven)
    OddOrEven.show()
    sys.exit(app.exec_())
